# permissions for end users to view myservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myservice-viewer-role
rules:
- apiGroups:
  - ssa.ymmt2005.github.io
  resources:
  - myservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ssa.ymmt2005.github.io
  resources:
  - myservices/status
  verbs:
  - get
